# Generated by Django 3.1 on 2021-02-23 15:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymess', '0022_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='pymess/e-mails/', verbose_name='content file'),
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='content',
            new_name='old_content',
        ),
    ]
