# Generated by Django 3.1 on 2021-02-23 15:24
from django.core.files.base import ContentFile
from django.db import migrations


def move_email_content_to_file(apps, schema_editor):
    EmailMessage = apps.get_model('pymess', 'EmailMessage')
    for message in EmailMessage.objects.all():
        message.content_file.save('content.txt', ContentFile(message.old_content.encode()))


class Migration(migrations.Migration):

    dependencies = [
        ('pymess', '0023_migration'),
    ]

    operations = [
        migrations.RunPython(move_email_content_to_file),
    ]
